README.md
addon/computed.js
addon/computeds/ago.js
addon/computeds/duration.js
addon/computeds/moment.js
addon/helpers/duration.js
app/initializers/ember-moment.js
bower.json
tests/dummy/app/controllers/index.js
tests/dummy/app/templates/index.hbs
tests/unit/computeds/ago-test.js
tests/unit/computeds/duration-test.js
tests/unit/helpers/duration-test.js

Based on PR: #24 
Adds `{{duration 4 'days'}}` helper as well as computed properties. See dummy test app for usage.

Add duration and clean up computeds code

---

README.md

This PR proposes updating the install command documented in the README to use the new `ember install:addon` command, decreasing the chances of user error.
**Cons**: not compatible with Ember CLI < 1.5.0.
Not sure whether you'd prefer to leave the README as is or change it.

Use ember install:addon

---

tests/unit/helpers/moment-test.js

The particular test that uses Date.parse to construct a unix timestamp was failing in the Australia/Melbourne timezone - the returned unix timestamp actually works out to be October 11 in Melbourne.

Failing Test in Australia/Melbourne

---

CHANGELOG.md
app/initializers/ember-moment.js
bower.json
package.json

I’m upgrading the bower/npm deps in line with ember-cli 0.1.15 produces.
Fixing HTMLBars register helper since Ember.HTMLBars.helper no longer exists

Version bump to 1.1.0, upgrading deps

---

README.md
addon/helpers/moment-duration.js
addon/helpers/moment-format.js
addon/helpers/moment-from-now.js
addon/helpers/moment-to-now.js
bower.json
tests/unit/helpers/moment-duration-test.js
tests/unit/helpers/moment-format-test.js
tests/unit/helpers/moment-from-now-test.js
tests/unit/helpers/moment-to-now-test.js

Can now pass locales as part of the helper, overriding the global option.
`{{moment-from-now date locale='fr'}}`

ability to add locale locally

---

addon/helpers/deprecated/ago.js
addon/helpers/deprecated/moment.js
addon/helpers/moment-format.js
addon/helpers/moment-from-now.js
addon/helpers/moment-to-now.js
addon/utils/compute-fn.js
app/helpers/ago.js
app/helpers/moment-format.js
app/helpers/moment-from-now.js
app/helpers/moment-to-now.js
app/helpers/moment.js
index.js
tests/dummy/app/controllers/index.js
tests/dummy/app/templates/index.hbs
tests/dummy/config/environment.js
tests/unit/helpers/moment-from-now-test.js
tests/unit/helpers/moment-to-now-test.js

#85 and #84 
Before I version, I plan to clean up the helpers a bit.  Separate < 1.13 helpers from >= 1.13 and include a build step to prune legacy vs modern.  This will clean up this change a bit more

Fixing allow empty, deprecated helper regression, fixes ember-beta and ember-canary

---

README.md

config.environment.js => config/environment.js

---

README.md

In my quick read of the docs I didn't see this syntax and was confused when I wasn't getting live updates. I think this makes it a bit more apparent/clear for a quick glance.

[DOC] Enhance Live Updating section for easier comprehension

---

CHANGELOG.md
README.md
addon/helpers/moment-relative.js
addon/modern/helpers/moment-relative.js
app/helpers/moment-relative.js
app/initializers/legacy-register.js
tests/dummy/app/templates/index.hbs
tests/unit/helpers/moment-relative-test.js

Using `{{moment-from-now}}` assumes the date is in the future.
Using `{{moment-to-now}}` assumes the date is in the past.
If the date is unknown (i.e. potentially in the past, potentially in the
future), use `{{moment-relative}}`.

Introduce `{{moment-relative}}`

---

addon/helpers/moment-duration.js
addon/helpers/moment-format.js
addon/helpers/moment-from-now.js
addon/helpers/moment-to-now.js
addon/modern/helpers/moment-duration.js
addon/modern/helpers/moment-format.js
addon/modern/helpers/moment-from-now.js
addon/modern/helpers/moment-to-now.js
app/initializers/legacy-register.js

Destructuring optional hashes affords at least two benefits:
* self documenting - obvious which options are available
* reduce noise - `hash.option` vs `option`

Destructure Hash params

---

tests/helpers/hours-from-now.js
tests/helpers/module-for-helper.js
tests/unit/computeds/from-now-test.js
tests/unit/computeds/to-now-test.js
tests/unit/helpers/moment-duration-test.js
tests/unit/helpers/moment-format-test.js
tests/unit/helpers/moment-from-now-test.js
tests/unit/helpers/moment-to-now-test.js

* Extract `moduleForHelper` to DRY up test setup
* Extract `hoursFromNow` to DRY up time arithmetic
* In tests, re-assign `this.container` and `this.registry` depending
upon what is available

Cleanup Test Suite

---

README.md
addon/helpers/-base.js
addon/helpers/moment-duration.js
addon/helpers/moment-format.js
addon/helpers/moment-from-now.js
addon/helpers/moment-to-now.js
app/services/moment.js
tests/dummy/app/controllers/index.js
tests/dummy/app/routes/index.js
tests/dummy/app/templates/index.hbs
tests/unit/helpers/moment-duration-test.js
tests/unit/helpers/moment-format-test.js
tests/unit/helpers/moment-from-now-test.js
tests/unit/helpers/moment-to-now-test.js

Give the following action, when invoked, will rerender all helpers which are using the global locale (ie, a locale was not passed as an attr).
Triggering a rerender of all helpers:
```js
export default Ember.Controller.extend({
moment: Ember.inject.service(),
actions: {
changeLocale(locale) {
this.get('moment').changeLocale(locale);
} 
});
````
Setting application-wide locale:
```js
// app/routes/application.js
export default Ember.Route.extend({
moment: Ember.inject.service(),
beforeModel() {
// default application-wide locale is spanish
this.get('moment').changeLocale('es');
}
});
```
Thoughts @stefanpenner ?
Part of #104

Add a service to manage global locale, and to rerender helpers on change

---

addon/helpers/-base.js
addon/helpers/moment-format.js
app/helpers/moment-format.js
app/instance-initializers/moment-default-format.js
app/services/moment.js
tests/dummy/app/controllers/index.js
tests/dummy/app/templates/index.hbs

This PR adds a `changeDefaultFormat` function to the moment service, as explained in #121. In order to stay compatible with the current way of setting a default format (in the config/environment.js), an instance initializer has been added to set the default format to the one specified there.
This means that the default format used by `{{moment-format myDate}}` can be changed at any time by calling:
```js
this.get("moment").changeDefaultFormat("DD.MM.YYYY");
```

Make it possible to change the default date format

---

README.md
addon/helpers/moment-calendar.js
app/helpers/moment-calendar.js
tests/unit/helpers/moment-calendar-test.js

Adds support for the `moment().calendar()` — Calendar Time display, and addresses https://github.com/stefanpenner/ember-moment/issues/126
```hbs
{{moment-calendar aDate}}
{{moment-calendar aDate optionalReferenceDate locale="es" timeZone="Australia/Sydney"}}
```
Produces such outputs as:
- Today at 2:36 PM
- Yesterday at 2:36 PM
- Tomorrow at 2:36 PM
- Sunday at 2:36 PM
- Last Monday at 2:36 PM
- 7/10/2011

Added support for moment().calendar() with moment-calendar

---

README.md
addon/computeds/-base.js
addon/computeds/calendar.js
addon/computeds/duration.js
addon/computeds/format.js
addon/computeds/from-now.js
addon/computeds/humanize.js
addon/computeds/locale.js
addon/computeds/moment.js
addon/computeds/to-now.js
addon/computeds/tz.js
tests/dummy/app/controllers/index.js
tests/dummy/app/styles/app.css
tests/dummy/app/templates/application.hbs
tests/dummy/app/templates/index.hbs
tests/dummy/app/templates/partials/calendar.hbs
tests/dummy/app/templates/partials/cps.hbs
tests/dummy/app/templates/partials/duration.hbs
tests/dummy/app/templates/partials/format.hbs
tests/dummy/app/templates/partials/from-now.hbs
tests/dummy/app/templates/partials/to-now.hbs
tests/helpers/hours-from-now.js
tests/unit/computeds/calendar-test.js
tests/unit/computeds/duration-test.js
tests/unit/computeds/format-test.js
tests/unit/computeds/from-now-test.js
tests/unit/computeds/moment-test.js
tests/unit/computeds/to-now-test.js
tests/unit/helpers/moment-from-now-test.js
tests/unit/helpers/moment-to-now-test.js

* https://github.com/stefanpenner/ember-moment/wiki/Computed-Property-Macros
Fixes #135
This is API breaking due to the duration computed having to be split out into duration + humanize in order to have the ability to localize duration before humanizing through composition.
```
durationExample: humanize(locale(duration(10, 'hours'), 'fr')) // => 10 heures
```

Adding locale and moment computeds

---

addon/services/moment.js

Unless I'm seeing it wrong it's harder than it should be to check if an object is a moment object.
The only way I'm able to check it is if I use moment from ``import moment from 'moment'`` in my code alongside importing the service.
I could just use the moment library directly without the service but the service already has the correct timezone.
This added method to the service would be very handy.

Add a shortcut for isMoment

---

addon/helpers/moment-format.js
addon/services/moment.js

* Only passes a format argument to `moment.format()` if one has been passed to the helper, or if `defaultFormat` has been set
* Removes initializer that automatically sets `defaultFormat` to `"LLLL"`
Fixes #161

Support formatting to ISO 8601 instead of forcing default LLLL

---

addon/helpers/now.js
tests/unit/helpers/now-test.js

`now` helper now returns `moment.now` instead of `new Date()`

Now helper uses moment.now

---

addon/computeds/calendar.js
addon/helpers/moment-calendar.js
tests/unit/helpers/moment-calendar-test.js

Fixes #176
Adds the ability to pass format object or individual format properties as attributes.
```js
this.setProperties({
date: moment('2013-01-01T02:30:26Z'),
referenceDate: moment('2013-01-01T12:00:00Z'),
formats:  {
sameDay: '[Today]',
nextDay: '[Tomorrow]',
nextWeek: 'dddd',
lastDay: '[Yesterday]',
lastWeek: '[Last] dddd',
sameElse: 'DD/MM/YYYY'
}
});
// full object
this.render(hbs`{{moment-calendar date referenceDate formats}}`);
// individual attrs
this.render(hbs`{{moment-calendar date referenceDate sameDay='[Today]' nextDay='[Tomorrow]'}}`);
```

moment-calendar accepts format param and hash values

---

addon/computeds/-base.js
addon/computeds/format.js
addon/helpers/-base.js
addon/utils/get-owner.js
package.json
tests/dummy/app/controllers/test-subject.js
tests/unit/computeds/calendar-test.js
tests/unit/computeds/duration-test.js
tests/unit/computeds/format-test.js
tests/unit/computeds/from-now-test.js
tests/unit/computeds/moment-test.js
tests/unit/computeds/to-now-test.js

Related to a comment on #163
The other alternative is to send a PR to ember-getowner-polyfill to exclude itself if the target Ember version contains getOwner.
/cc @stefanpenner @rwjblue 
Feel free to comment, I am happy to work on whatever alternative you propose even after this is merged.

Removing ember-getowner-polyfill as a direct dep

---

addon/helpers/moment-add.js
addon/helpers/moment-subtract.js
tests/unit/helpers/moment-add-test.js
tests/unit/helpers/moment-subtract-test.js

- Updated helpers moment-add and moment-subtract to use the moment service to persist the locale change on the service. 
- Added the moment service into each of the tests for both helpers.
Reference issue #196

converted moment-subtract and moment-add to use moment service

---

addon/services/moment.js
tests/integration/moment-test.js

Adding updateLocale method to moment service
`moment.updateLocale()` - https://momentjs.com/docs/#/customization/
My use case required globally configuring moment weeks to start on a different weekday.  I'm not very familiar with the service/addon so feedback + suggestions are greatly appreciated!

Add updateLocale to moment service

---

README.md
addon/helpers/moment-format.js

Hello,
I am new to Ember and I was relatively confused by the Helpers documentation of the README. Since I am perhaps [not the only one](https://github.com/stefanpenner/ember-moment/issues/153), I took a stab at detailing the README some more.
I discovered a couple of weird things doing so however. I am probably missing something obvious but it would be great if I could be enlightened (so I can further improve the README):
- Why are `locale` and `timeZone` optional named parameter? If I don't have the `locale`/`timeZone` in my global configuration, passing them in a helper does not help parsing the string, and if I *do* have them in my global configuration, then I can parse a string without them. Disambiguation maybe?
- `hideSuffix/hidePrefix` would it be worthwhile having a single named …

Improve README (especially for Helpers)

---

README.md
addon/helpers/moment-from-now.js
addon/helpers/moment-from.js
addon/helpers/moment-to-now.js
addon/helpers/moment-to.js
tests/unit/helpers/moment-from-now-test.js
tests/unit/helpers/moment-from-test.js
tests/unit/helpers/moment-to-now-test.js
tests/unit/helpers/moment-to-test.js

This is addressing point number 2 from previous pull request.
- `moment-to` and `moment-from` helpers can now also hide affix.
- tests have been added.
- I changed the requirements in the README to reflect `package.json` - is this appropriate? (why is `ember-cli` a devDependency and not a dependency?)
- Simplified the README
- Technically `moment-from-now` and `moment-to-now` helpers are not needed anymore. Should we deprecate them as well (point number 3)?
thanks!

Deprecate hide(Suff/Pref)ix for hideAffix + update requirements

---

README.md
addon/computeds/utc.js
addon/helpers/utc.js
addon/services/moment.js
app/helpers/utc.js
tests/dummy/app/templates/partials/format.hbs
tests/dummy/app/templates/partials/moment.hbs
tests/unit/helpers/utc-test.js

Adds support for moment.utc so that you can do things like:
```hbs
{{utc interval=1000}}
{{utc (moment now)}}    {{!-- Mon Feb 12 2018 21:30:20 GMT+0000 --}}
{{moment-format (utc) 'YYYY-MM-DD HH:mm:ss Z'}}    {{!-- 2018-02-12 21:30:20 +00:00 --}}
{{utc '2018-01-01T00:00:00+01:00' 'YYYY-MM-DD HH:mm:ssZ'}}  {{!-- Sun Dec 31 2017 23:00:00 GMT+0000 --}}
```
Also included a utc computed property macro, which I think takes care of Issue #270 .

add utc helper and computed property macro

---

yarn.lock

one of the versions of `moment` was wrong in the `yarn.lock`

consistent yarn.lock

---

addon/helpers/moment-calendar.js

Solves Ember deprecation https://deprecations-app-prod.herokuapp.com/deprecations/v3.x/#toc_ember-polyfills-deprecate-merge

Substitute merge() with assign() - Ember deprecation

---

addon/computeds/calendar.js

https://deprecations.emberjs.com/v3.x/#toc_ember-polyfills-deprecate-merge
This one was missed in #296

Replace merge with assign

---

.travis.yml
package.json
yarn.lock

I had conflict versions of `browserslist` dependency in my `ember-cli-postcss` pipeline and I wasn"t able to use a query like `> .2% and lastest 2 versions`... because `ember-moment` use an old version of `ember-macro-helpers` which use an old version of `ember-weakmap` which use an old version of `browserslist` (v3.x) ... :D
⚠️ The latest ember-macro-helpers needs to run at least on node v8.*  ... so I guess if we merge this PR, a major version of ember-moment will come.
Temporary, I fixed it in my project by using an up-to-date version of browserstlist in my package.json but this was a real headache to understand what happened.
---

[BREAKING] Update ember-macro-helpers version, drops Node 6 support

---

blueprints/ember-moment/index.js

Hi!
The unsupported signature of the [`addAddonToProject`](https://ember-cli.com/api/classes/Blueprint.html#method_addAddonToProject) method is used, as a result of which the latest version of `ember-cli-moment-shim` installed.
~We have an application running on `ember-cli@2.4.3`, and we cannot update it due to various dependencies.~
~Is it possible to make the same fixes for `ember-moment@7.0.1` and release the new version `7.0.2`?~
I did not notice that versions `7.0.2` and `7.0.3` have already been published.
In any case, it doesn’t matter anymore, the problem is resolved, thanks.

Fix install ember-cli-moment-shim in addon blueprint

---

addon/helpers/moment-from-now.js
tests/unit/helpers/moment-from-now-test.js

Since https://github.com/emberjs/ember.js/pull/19133, ember-source requires passing a `since` option to the `deprecate` function. Since this deprecation is targeted for removal in 8.0 anyway, seems like we can just remove it instead of fixing the issue.

Remove deprecated feature

---

app/services/moment.js

Fixes https://github.com/adopted-ember-addons/ember-moment/issues/362
Current implementation throws `TypeError` for `undefined` if `config.moment.outputFormat` is not specified.
- checks for presence of `config.moment` and `config.moment.outputFormat`
- set value if present, fall back to `null` otherwise

`MomentOverride.defaultFormat` null if not defined in config

---

package.json

This should fix `release-plan`.
It was a incident while v2 addon migration #411

Readd `repository` to root `package.json`

---

ember-moment/src/helpers/-base.js
test-app-3.x/app/controllers/index.js
test-app-3.x/app/routes/application.js
test-app-3.x/app/routes/index.js
test-app-4.x/app/controllers/index.js
test-app-4.x/app/routes/application.js
test-app-4.x/app/routes/index.js
test-app-5.x/app/controllers/index.js
test-app-5.x/app/routes/application.js
test-app-5.x/app/routes/index.js

import service instead of inject from '@ember/service'
