adopted-ember-addons/ember-moment

Brocfile.js
app/initializers/ember-moment.js
bower.json
package.json
tests/helpers/run-append.js
tests/unit/helpers/moment-test.js

[Bugfix] ember-moment with HTMLBars now uses bound helpers

---

app/initializers/init-moment.js

Fixes #50 
I'll add smoke tests tonight to prevent regressions.

Use registerHelper for <= 1.12

---

.travis.yml
addon/computeds/ago.js
addon/computeds/duration.js
addon/computeds/moment.js
addon/helpers/ago.js
addon/helpers/duration.js
addon/helpers/moment.js
addon/utils/is-descriptor.js
addon/utils/make-bound-helper.js
app/helpers/ago.js
app/helpers/duration.js
app/helpers/moment.js
bower.json
config/ember-try.js
tests/acceptance/smoke-test.js
tests/dummy/app/controllers/smoke.js
tests/dummy/app/router.js
tests/dummy/app/routes/smoke.js
tests/dummy/app/templates/smoke.hbs

* Fixes 1.10.0
* Adds 1.10->1.13 into the test matrix
* Adds smoke tests to cover initializer logic

adding smoke tests to catch initializer logic

---

README.md
blueprints/ember-moment/index.js
package.json

upgrading shim to bring in ability to include all locales

---

README.md
addon/computeds/to-now.js
addon/helpers/moment-to-now.js
app/helpers/moment-to-now.js
app/initializers/legacy-register.js
bower.json
tests/unit/computeds/duration-test.js
tests/unit/computeds/from-now-test.js
tests/unit/computeds/moment-computed-test.js
tests/unit/computeds/to-now-test.js
tests/unit/helpers/moment-duration-test.js
tests/unit/helpers/moment-format-test.js
tests/unit/helpers/moment-to-now-test.js

[Enhancement] add toNow helper and computed

---

README.md
addon/computeds/duration.js
addon/computeds/format.js
addon/computeds/from-now.js
addon/computeds/to-now.js
addon/helpers/moment-duration.js
addon/helpers/moment-format.js
addon/helpers/moment-from-now.js
addon/helpers/moment-to-now.js
app/helpers/moment-format.js
package.json
tests/dummy/app/controllers/index.js
tests/dummy/config/environment.js
tests/unit/helpers/moment-format-test.js

Initial commit to add global format output

---

README.md
addon/helpers/moment-duration.js
addon/helpers/moment-format.js
addon/helpers/moment-from-now.js
addon/helpers/moment-to-now.js
addon/utils/compute-fn.js
tests/unit/helpers/moment-duration-test.js
tests/unit/helpers/moment-format-test.js
tests/unit/helpers/moment-from-now-test.js
tests/unit/helpers/moment-to-now-test.js

`{{moment-format date allowEmpty=true}}`
date = null || undefined || ''
Fixes #42

adding allowEmpty so that null is allowable

---

addon/helpers/moment-from-now.js
addon/helpers/moment-to-now.js
bower.json

[Bugfix] fixing the timer for interval

---

addon/helpers/deprecated/ago.js
addon/helpers/moment-format.js
addon/helpers/moment-from-now.js
addon/helpers/moment-to-now.js
addon/utils/compute-fn.js
app/helpers/ago.js
app/helpers/moment-format.js
app/helpers/moment-from-now.js
app/helpers/moment-to-now.js
app/helpers/moment.js
tests/dummy/app/controllers/index.js
tests/dummy/app/templates/index.hbs
tests/dummy/config/environment.js
tests/unit/helpers/moment-from-now-test.js
tests/unit/helpers/moment-to-now-test.js

as discussed in https://github.com/stefanpenner/ember-moment/issues/84, an allowEmpty global config to be used throughout application, let me know your thoughts

adding global allowEmpty config 

---

addon/modern/helpers/moment-format.js
app/modern/helpers/moment-format.js

fixes #89 
Don't have a good way to write a test to cover this because of the way the helpers are registered.

globalOutputFormat typo, broke global output format

---

CHANGELOG.md
blueprints/ember-moment/index.js
package.json

bumping ember-cli-moment-shim to warn on mismatch locales

---

addon/computeds/format.js

Fix typo in computeds/format.js

---

.travis.yml
tests/unit/computeds/moment-computed-test.js

Adding coverage for output format

---

.travis.yml
addon/helpers/-base.js
addon/helpers/moment-format.js
app/instance-initializers/moment-default-format.js
app/services/moment.js
config/ember-try.js
tests/dummy/app/controllers/index.js
tests/unit/helpers/moment-format-test.js

Tweaking logic for default format and writing a test to cover functionality

---

addon/utils/compute-fn.js

It should only warn about missing dates if `allowEmpty` is false.

Do not warn about missing date when `allowEmpty`

---

addon/computeds/-base.js
addon/computeds/duration.js
addon/computeds/format.js
addon/computeds/from-now.js
addon/computeds/to-now.js

Removing duplicated logic around building out the computed params and building the dep key array.

Cleaning up previous commits

---

addon/computeds/-base.js
addon/computeds/duration.js
addon/computeds/format.js
addon/computeds/from-now.js
addon/computeds/to-now.js
addon/utils/get-dependent-keys.js
addon/utils/get-value.js
addon/utils/is-descriptor.js
tests/unit/helpers/moment-format-test.js
tests/unit/utils/is-descriptor.js

I will work on the locale computed tonight, just addressing immediate concerns with computed composition

Baseline for the locale support

---

addon/helpers/moment-calendar.js
app/helpers/moment-calendar.js

{{moment-calendar}} should respect `allowEmpty` config option

---

addon/helpers/-base.js
addon/helpers/moment-calendar.js
addon/helpers/moment-duration.js
addon/helpers/moment-format.js
addon/helpers/moment-from-now.js
addon/helpers/moment-to-now.js
addon/helpers/now.js
app/helpers/moment-calendar.js
app/helpers/now.js
tests/dummy/app/controllers/index.js
tests/dummy/app/controllers/smoke.js
tests/dummy/app/templates/partials/calendar.hbs
tests/dummy/app/templates/partials/format.hbs
tests/dummy/app/templates/partials/from-now.hbs
tests/dummy/app/templates/partials/to-now.hbs
tests/dummy/app/templates/smoke.hbs

`{{moment-format (now interval=1000) 'MMMM Do YYYY, h:mm:ss a'}}`
But also adds the interval option to all helpers.

Adding interval to all helpers and a new 'now' helper

---

addon/helpers/is-after.js
addon/helpers/is-before.js
addon/helpers/is-between.js
addon/helpers/is-same-or-after.js
addon/helpers/is-same-or-before.js
addon/helpers/is-same.js
app/helpers/is-after.js
app/helpers/is-before.js
app/helpers/is-between.js
app/helpers/is-same-or-after.js
app/helpers/is-same-or-before.js
app/helpers/is-same.js
tests/unit/helpers/is-after-test.js
tests/unit/helpers/is-before-test.js
tests/unit/helpers/is-between-test.js
tests/unit/helpers/is-same-or-after-test.js
tests/unit/helpers/is-same-or-before-test.js
tests/unit/helpers/is-same-test.js

These are the query helpers mentioned in #163.

Add query helpers.

---

addon/helpers/moment-to-date.js
app/helpers/moment-to-date.js

add moment-to-date helper

---

.travis.yml
config/ember-try.js

Test against ember-alpha also.

---

README.md
addon/helpers/unix.js
app/helpers/unix.js
tests/dummy/app/controllers/index.js
tests/dummy/app/templates/partials/format.hbs
tests/unit/helpers/unix-test.js

This PR adds the `moment.unix` helper as described in https://github.com/stefanpenner/ember-moment/issues/189.
Note, I'll have a separate PR to update some existing documentation discrepancies.

[Feature] Add unix helper

---

CHANGELOG.md
README.md
addon/services/moment.js
tests/integration/moment-test.js

Fixes #196
/cc @mfeltz but still feel free to submit the PR so the helpers use the service-scoped locale as you mentioned.  This PR makes it less necessary, but would be good for consistency :)

Global moment locale

---

addon/helpers/is-after.js
addon/helpers/is-before.js
addon/helpers/is-between.js
addon/helpers/is-same-or-after.js
addon/helpers/is-same-or-before.js
addon/helpers/is-same.js
addon/helpers/moment-calendar.js
addon/helpers/moment-duration.js
addon/helpers/moment-format.js
addon/helpers/moment-from-now.js
addon/helpers/moment-from.js
addon/helpers/moment-to-date.js
addon/helpers/moment-to-now.js
addon/helpers/moment-to.js
addon/helpers/moment.js
addon/helpers/now.js
addon/helpers/unix.js
tests/unit/helpers/is-after-test.js
tests/unit/helpers/is-between-test.js
tests/unit/helpers/is-same-or-after-test.js
tests/unit/helpers/moment-calendar-test.js
tests/unit/helpers/moment-from-now-test.js
tests/unit/helpers/moment-from-test.js
tests/unit/helpers/moment-to-now-test.js
tests/unit/helpers/moment-to-test.js
tests/unit/helpers/now-test.js

Updated the rest of the helpers to user the moment service, as well as the tests to provide consistency.

included use of moment service in the rest of the helpers and tests

---

package.json
yarn.lock

Update "ember-cli-babel" to v6.6.0

---

.travis.yml

- line endings
- node version with a working npm

Tidy-up travis.yml

---

.eslintrc.js
.gitignore
.npmignore
.travis.yml
addon/services/moment.js
bower.json
config/ember-try.js
config/environment.js
ember-cli-build.js
index.js
package.json
testem.js
tests/dummy/app/app.js
tests/dummy/app/controllers/index.js
tests/dummy/app/controllers/smoke.js
tests/dummy/app/index.html
tests/dummy/config/environment.js
tests/dummy/config/targets.js
tests/helpers/module-for-acceptance.js
tests/helpers/start-app.js
tests/index.html
tests/test-helper.js
yarn.lock

Upgrading ember-cli and its dependencies

---

package.json

https://nvd.nist.gov/vuln/detail/CVE-2017-18214

bump version of moment to 2.19.3 and above

---

addon/services/moment.js
addon/utils/helper-compute.js

Found the Logger deprecation warnings upon upgrading to Ember 3.2

Replace Logger with console

---

CONTRIBUTING.md
README.md

* Move contributing instructions away from README.md to CONTRIBUTING.md.
* add a table of contents to README.md
Closes https://github.com/stefanpenner/ember-moment/issues/304

Readme cleanup + Table of contents

---

README.md

I have been using this package for a long time and didn't know these helpers existed/got added! Took a few minutes to add come docs when I saw the open issue.
Let me know if anything else should be mentioned.
This closes https://github.com/stefanpenner/ember-moment/issues/300

📝Add moment-add and moment-subtract helper usage to docs

---

README.md

Requesting this because it took me a long time to work out how to achieve this functionality. I only found the answer by searching the issues - https://github.com/stefanpenner/ember-moment/issues/282

Update readme with an example of how to use moment format with (now)

---

addon/computeds/format.js
tests/acceptance/smoke-test.js
tests/integration/moment-test.js
tests/unit/computeds/calendar-test.js
tests/unit/computeds/duration-test.js
tests/unit/computeds/format-test.js
tests/unit/computeds/from-now-test.js
tests/unit/computeds/moment-test.js
tests/unit/computeds/test-helpers.js
tests/unit/computeds/to-now-test.js
tests/unit/helpers/is-after-test.js
tests/unit/helpers/is-before-test.js
tests/unit/helpers/is-between-test.js
tests/unit/helpers/is-same-or-after-test.js
tests/unit/helpers/is-same-or-before-test.js
tests/unit/helpers/is-same-test.js
tests/unit/helpers/moment-add-test.js
tests/unit/helpers/moment-calendar-test.js
tests/unit/helpers/moment-diff-test.js
tests/unit/helpers/moment-duration-test.js
tests/unit/helpers/moment-format-test.js
tests/unit/helpers/moment-from-now-test.js
tests/unit/helpers/moment-from-test.js
tests/unit/helpers/moment-to-now-test.js
tests/unit/helpers/moment-to-test.js
tests/unit/helpers/now-test.js
tests/unit/helpers/unix-test.js
tests/unit/helpers/utc-test.js

@NullVoxPopuli I hope this help. Current state running the test suite locally:

Make more progress on tests

---

addon/helpers/-base.js

supersedes https://github.com/adopted-ember-addons/ember-moment/pull/351

fix Ember.computed.bool is not a function

---

package.json
test-app/package.json
test-app/yarn.lock
yarn.lock

This is the 2nd PR to fix CI
Next steps are described here https://github.com/adopted-ember-addons/ember-moment/pull/378#issuecomment-2186899845

Add `@ember/string` to devDependency

---

CHANGELOG.md

It was dropped as fail while #411

Recover `CHANGELOG.md`
